name: Autograde R function

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install testthat
        run: |
          Rscript -e 'install.packages("testthat", repos="https://cloud.r-project.org")'

      - name: Run tests
        run: |
          Rscript tests/run_tests.R | tee test-report.txt

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt
